runtime: nodejs16
service: vpi
env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic